[2023-12-27T15:57:05.348+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: modeling_dag.predict_ntu_task scheduled__2023-12-27T15:56:00+00:00 [queued]>
[2023-12-27T15:57:05.354+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: modeling_dag.predict_ntu_task scheduled__2023-12-27T15:56:00+00:00 [queued]>
[2023-12-27T15:57:05.354+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-12-27T15:57:05.365+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): predict_ntu_task> on 2023-12-27 15:56:00+00:00
[2023-12-27T15:57:05.370+0000] {standard_task_runner.py:57} INFO - Started process 425 to run task
[2023-12-27T15:57:05.373+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'modeling_dag', 'predict_ntu_task', 'scheduled__2023-12-27T15:56:00+00:00', '--job-id', '392', '--raw', '--subdir', 'DAGS_FOLDER/modeling.py', '--cfg-path', '/tmp/tmpza8b7syu']
[2023-12-27T15:57:05.375+0000] {standard_task_runner.py:85} INFO - Job 392: Subtask predict_ntu_task
[2023-12-27T15:57:05.408+0000] {task_command.py:410} INFO - Running <TaskInstance: modeling_dag.predict_ntu_task scheduled__2023-12-27T15:56:00+00:00 [running]> on host c56b1de7f6cf
[2023-12-27T15:57:05.461+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='modeling_dag' AIRFLOW_CTX_TASK_ID='predict_ntu_task' AIRFLOW_CTX_EXECUTION_DATE='2023-12-27T15:56:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-27T15:56:00+00:00'
[2023-12-27T15:57:05.469+0000] {logging_mixin.py:150} INFO - [[6.883569], [6.713672], [6.362846]]
[2023-12-27T15:57:05.470+0000] {modeling.py:58} INFO - [[6.883569], [6.713672], [6.362846]]
[2023-12-27T15:57:05.991+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  "X does not have valid feature names, but"

[2023-12-27T15:57:06.688+0000] {logging_mixin.py:150} INFO - 1/1 [==============================] - ETA: 0s
[2023-12-27T15:57:06.688+0000] {logging_mixin.py:150} INFO - 1/1 [==============================] - 1s 660ms/step
[2023-12-27T15:57:06.690+0000] {logging_mixin.py:150} INFO - new data : [[6.883569], [6.713672], [6.362846]]
[2023-12-27T15:57:06.690+0000] {logging_mixin.py:150} INFO - t+1 ntu : [5.204199]
[2023-12-27T15:57:06.690+0000] {logging_mixin.py:150} INFO - <class 'numpy.ndarray'>
[2023-12-27T15:57:06.690+0000] {python.py:183} INFO - Done. Returned value was: [5.204199]
[2023-12-27T15:57:06.708+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=modeling_dag, task_id=predict_ntu_task, execution_date=20231227T155600, start_date=20231227T155705, end_date=20231227T155706
[2023-12-27T15:57:06.749+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-12-27T15:57:06.771+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
