[2023-10-21T22:34:20.887+0900] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: combined_dag.load_modeling scheduled__2023-10-21T13:32:00+00:00 [queued]>
[2023-10-21T22:34:20.896+0900] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: combined_dag.load_modeling scheduled__2023-10-21T13:32:00+00:00 [queued]>
[2023-10-21T22:34:20.897+0900] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-10-21T22:34:20.908+0900] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): load_modeling> on 2023-10-21 13:32:00+00:00
[2023-10-21T22:34:20.914+0900] {standard_task_runner.py:57} INFO - Started process 144557 to run task
[2023-10-21T22:34:20.917+0900] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'combined_dag', 'load_modeling', 'scheduled__2023-10-21T13:32:00+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/combined_dag(real).py', '--cfg-path', '/tmp/tmpiv_r7x5j']
[2023-10-21T22:34:20.917+0900] {standard_task_runner.py:85} INFO - Job 52: Subtask load_modeling
[2023-10-21T22:34:21.182+0900] {task_command.py:410} INFO - Running <TaskInstance: combined_dag.load_modeling scheduled__2023-10-21T13:32:00+00:00 [running]> on host DESKTOP-HIRTBK6.
[2023-10-21T22:34:21.573+0900] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='combined_dag' AIRFLOW_CTX_TASK_ID='load_modeling' AIRFLOW_CTX_EXECUTION_DATE='2023-10-21T13:32:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-21T13:32:00+00:00'
[2023-10-21T22:34:21.660+0900] {logging_mixin.py:150} INFO - /home/user/airflow
[2023-10-21T22:34:21.660+0900] {combined_dag(real).py:158} INFO - /home/user/airflow
[2023-10-21T22:34:22.959+0900] {logging_mixin.py:150} WARNING - /home/user/anaconda3/envs/airflow_env/lib/python3.7/site-packages/sklearn/base.py:451 UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
[2023-10-21T22:34:23.014+0900] {logging_mixin.py:150} WARNING - /home/user/anaconda3/envs/airflow_env/lib/python3.7/site-packages/sklearn/base.py:451 UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
[2023-10-21T22:34:23.693+0900] {logging_mixin.py:150} WARNING - /home/user/anaconda3/envs/airflow_env/lib/python3.7/site-packages/sklearn/base.py:451 UserWarning: X does not have valid feature names, but ExtraTreesRegressor was fitted with feature names
[2023-10-21T22:34:23.698+0900] {python.py:183} INFO - Done. Returned value was: (array([26.43616185]), array([0]))
[2023-10-21T22:34:23.893+0900] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=combined_dag, task_id=load_modeling, execution_date=20231021T133200, start_date=20231021T133420, end_date=20231021T133423
[2023-10-21T22:34:23.980+0900] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-10-21T22:34:24.117+0900] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
