[2023-12-27T17:45:02.067+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: modeling_dag.predict_ntu_task scheduled__2023-12-27T17:44:00+00:00 [queued]>
[2023-12-27T17:45:02.073+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: modeling_dag.predict_ntu_task scheduled__2023-12-27T17:44:00+00:00 [queued]>
[2023-12-27T17:45:02.073+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-12-27T17:45:02.083+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): predict_ntu_task> on 2023-12-27 17:44:00+00:00
[2023-12-27T17:45:02.088+0000] {standard_task_runner.py:57} INFO - Started process 2864 to run task
[2023-12-27T17:45:02.090+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'modeling_dag', 'predict_ntu_task', 'scheduled__2023-12-27T17:44:00+00:00', '--job-id', '632', '--raw', '--subdir', 'DAGS_FOLDER/modeling.py', '--cfg-path', '/tmp/tmpf4_11r7o']
[2023-12-27T17:45:02.092+0000] {standard_task_runner.py:85} INFO - Job 632: Subtask predict_ntu_task
[2023-12-27T17:45:02.123+0000] {task_command.py:410} INFO - Running <TaskInstance: modeling_dag.predict_ntu_task scheduled__2023-12-27T17:44:00+00:00 [running]> on host c56b1de7f6cf
[2023-12-27T17:45:02.182+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='modeling_dag' AIRFLOW_CTX_TASK_ID='predict_ntu_task' AIRFLOW_CTX_EXECUTION_DATE='2023-12-27T17:44:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-27T17:44:00+00:00'
[2023-12-27T17:45:09.611+0000] {warnings.py:110} WARNING - /opt/***/dags/modeling.py:40: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lstm_df[col] = low_val

[2023-12-27T17:45:10.269+0000] {logging_mixin.py:150} INFO - new_ntu_data [[4.318874999999999], [4.289369], [4.099634]]
[2023-12-27T17:45:10.269+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  "X does not have valid feature names, but"

[2023-12-27T17:45:10.270+0000] {logging_mixin.py:150} INFO - ss_ntu_data [[0.02700572]
 [0.02693764]
 [0.02649986]]
[2023-12-27T17:45:10.870+0000] {logging_mixin.py:150} INFO - 1/1 [==============================] - ETA: 0s
[2023-12-27T17:45:10.870+0000] {logging_mixin.py:150} INFO - 1/1 [==============================] - 1s 568ms/step
[2023-12-27T17:45:10.872+0000] {logging_mixin.py:150} INFO - new data : [[4.318874999999999], [4.289369], [4.099634]]
[2023-12-27T17:45:10.872+0000] {logging_mixin.py:150} INFO - t+1 ntu : [3.1215608]
[2023-12-27T17:45:10.872+0000] {logging_mixin.py:150} INFO - <class 'numpy.ndarray'>
[2023-12-27T17:45:10.876+0000] {python.py:183} INFO - Done. Returned value was: [3.1215608]
[2023-12-27T17:45:10.893+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=modeling_dag, task_id=predict_ntu_task, execution_date=20231227T174400, start_date=20231227T174502, end_date=20231227T174510
[2023-12-27T17:45:10.928+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-12-27T17:45:10.945+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
