[2024-02-05T06:46:53.856+0000] {taskinstance.py:1097} INFO - Dependencies not met for <TaskInstance: modeling_dag.consume_task scheduled__2024-02-04T16:52:00+00:00 [failed]>, dependency 'Task Instance State' FAILED: Task is in the 'failed' state.
[2024-02-05T06:46:53.871+0000] {local_task_job_runner.py:154} INFO - Task is not able to be run
